version: "3.7"
services: 
    mariadb:
        image: mariadb
        container_name: mariadb_beta
        ports:
            - 3307:3306
        environment: 
            - MYSQL_DATABASE=jwt
            - MYSQL_USER=rooti
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root